#
# Usage:
#   $ limactl start default.yaml
#
# See https://github.com/lima-vm/lima/blob/master/examples/docker.yaml
#

cpus: 4
memory: 4GiB
disk: 20GiB

images:
  - location: https://cloud-images.ubuntu.com/hirsute/current/hirsute-server-cloudimg-amd64.img
    arch: x86_64
  - location: https://cloud-images.ubuntu.com/hirsute/current/hirsute-server-cloudimg-arm64.img
    arch: aarch64

mounts:
  - location: "~"
    writable: false
  - location: /tmp/lima
    writable: true

ssh:
  localPort: 60006
  loadDotSSHPubKeys: true

containerd:
  system: false
  user: false

provision:
  - mode: system
    script: |
      #!/bin/bash
      set -eux -o pipefail
      command -v docker >/dev/null 2>&1 && exit 0
      export DEBIAN_FRONTEND=noninteractive
      curl -fsSL https://get.docker.com | sh
      HOST_GATEWAY=$(grep host.lima.internal /etc/hosts | awk '{ print $1 }')
      mkdir -p /etc/systemd/system/docker.service.d/
      cat <<EOF > /etc/systemd/system/docker.service.d/override.conf
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd -H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock --host-gateway-ip=$HOST_GATEWAY
      EOF
      systemctl daemon-reload
      systemctl restart docker.service

probes:
  - script: |
      #!/bin/bash
      set -eux -o pipefail
      if ! timeout 30s bash -c "until command -v docker >/dev/null 2>&1; do sleep 3; done"; then
        echo >&2 "docker is not installed yet"
        exit 1
      fi
    hint: See "/var/log/cloud-init-output.log". in the guest
